using System.Text;

namespace Unicode.NET.CodeGen.Generation;

/// <summary>
/// Deterministic, diff-friendly C# source writer.
/// No generation timestamp — only the UCD version is recorded.
/// </summary>
public sealed class CodeWriter
{
  private readonly StringBuilder _sb = new();
  private int _indent = 0;
  private const string IndentUnit = "    ";

  // ── Header / footer ─────────────────────────────────────────────────────

  public void WriteFileHeader(string ucdVersion)
  {
    _sb.AppendLine("// <auto-generated />");
    _sb.AppendLine($"// Source: Unicode Character Database {ucdVersion}");
    _sb.AppendLine("// Do not edit — regenerate with: dotnet run --project tools/Unicode.NET.CodeGen -- update --version <version>");
    _sb.AppendLine();
    _sb.AppendLine("#nullable enable");
    _sb.AppendLine();
  }

  public void WriteUsing(string ns) => _sb.AppendLine($"using {ns};");
  public void WriteBlankLine() => _sb.AppendLine();

  public void WriteNamespaceOpen(string ns)
  {
    _sb.AppendLine($"namespace {ns};");
    _sb.AppendLine();
  }

  public void WriteClassOpen(string modifiers, string name)
  {
    AppendIndent();
    _sb.AppendLine($"{modifiers} class {name}");
    AppendIndent();
    _sb.AppendLine("{");
    _indent++;
  }

  public void WriteClassClose()
  {
    _indent--;
    AppendIndent();
    _sb.AppendLine("}");
  }

  public void WriteMethodOpen(string modifiers, string returnType, string signature)
  {
    AppendIndent();
    _sb.AppendLine($"{modifiers} {returnType} {signature}");
    AppendIndent();
    _sb.AppendLine("{");
    _indent++;
  }

  public void WriteMethodClose()
  {
    _indent--;
    AppendIndent();
    _sb.AppendLine("}");
  }

  public void WriteLine(string line)
  {
    AppendIndent();
    _sb.AppendLine(line);
  }

  public void WriteRaw(string text) => _sb.Append(text);

  private void AppendIndent()
  {
    for (int i = 0; i < _indent; i++)
      _sb.Append(IndentUnit);
  }

  public string GetContent() => _sb.ToString();
}
